import { useEffect, useMemo, useState } from 'react';
import { NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { Activity, Bell, ChevronRight, CloudSun, Droplets, Leaf, Menu, Moon, Sprout, Sun, TrendingUp, Wheat, X, Zap } from 'lucide-react';
import { requestJson } from './lib/api';

const navItems = [
  { to: '/', label: 'Overview', icon: Activity },
  { to: '/fields', label: 'My fields', icon: Wheat },
  { to: '/recommendations', label: 'Recommendations', icon: Sprout },
  { to: '/insights', label: 'Insights', icon: TrendingUp },
  { to: '/weather', label: 'Weather station', icon: CloudSun },
  { to: '/settings', label: 'Settings', icon: Zap },
];

const services = [
  { key: 'crop', title: 'Crop recommendation', description: 'Match soil and climate conditions to a crop.', icon: Sprout, tone: 'green' },
  { key: 'fertilizer', title: 'Fertilizer recommendation', description: 'Build a nutrient plan around your crop stage.', icon: Leaf, tone: 'purple' },
  { key: 'irrigation', title: 'Irrigation prediction', description: 'Know when your field needs water.', icon: Droplets, tone: 'blue' },
  { key: 'price', title: 'Price prediction', description: 'Estimate the next market price for a commodity.', icon: TrendingUp, tone: 'amber' },
  { key: 'yield', title: 'Yield prediction', description: 'Estimate output from your planting plan.', icon: Wheat, tone: 'orange' },
];

const formConfigs = {
  crop: { title: 'Crop recommendation', endpoint: '/crop/predict', resultKey: 'crop', resultLabel: 'Recommended crop', tone: 'green', fields: [['N', 'Nitrogen', 'number', '90'], ['P', 'Phosphorus', 'number', '42'], ['K', 'Potassium', 'number', '43'], ['temperature', 'Temperature (C)', 'number', '20.8'], ['humidity', 'Humidity (%)', 'number', '82'], ['ph', 'Soil pH', 'number', '6.5'], ['rainfall', 'Rainfall (mm)', 'number', '202.9']] },
  fertilizer: { title: 'Fertilizer recommendation', endpoint: '/fertilizer/predict', resultKey: 'fertilizer', resultLabel: 'Recommended fertilizer', tone: 'purple', fields: [['Soil_Type', 'Soil type', 'text', 'Loamy'], ['Soil_pH', 'Soil pH', 'number', '6.5'], ['Soil_Moisture', 'Soil moisture', 'number', '35'], ['Organic_Carbon', 'Organic carbon', 'number', '1.2'], ['Electrical_Conductivity', 'Electrical conductivity', 'number', '0.4'], ['Nitrogen_Level', 'Nitrogen level', 'number', '45'], ['Phosphorus_Level', 'Phosphorus level', 'number', '30'], ['Potassium_Level', 'Potassium level', 'number', '40'], ['Temperature', 'Temperature (C)', 'number', '25'], ['Humidity', 'Humidity (%)', 'number', '60'], ['Rainfall', 'Rainfall (mm)', 'number', '120'], ['Crop_Type', 'Crop type', 'text', 'Rice'], ['Crop_Growth_Stage', 'Growth stage', 'text', 'Vegetative'], ['Season', 'Season', 'text', 'Kharif'], ['Irrigation_Type', 'Irrigation type', 'text', 'Drip'], ['Previous_Crop', 'Previous crop', 'text', 'Wheat'], ['Region', 'Region', 'text', 'Central'], ['Fertilizer_Used_Last_Season', 'Fertilizer last season', 'number', '40'], ['Yield_Last_Season', 'Yield last season', 'number', '3.2']] },
  irrigation: { title: 'Irrigation prediction', endpoint: '/irrigation/predict', resultKey: 'irrigation_need', resultLabel: 'Irrigation need', tone: 'blue', fields: [['Soil_Type', 'Soil type', 'text', 'Loamy'], ['Soil_pH', 'Soil pH', 'number', '6.5'], ['Soil_Moisture', 'Soil moisture', 'number', '35'], ['Organic_Carbon', 'Organic carbon', 'number', '1.2'], ['Electrical_Conductivity', 'Electrical conductivity', 'number', '0.4'], ['Temperature_C', 'Temperature (C)', 'number', '25'], ['Humidity', 'Humidity (%)', 'number', '60'], ['Rainfall_mm', 'Rainfall (mm)', 'number', '120'], ['Sunlight_Hours', 'Sunlight hours', 'number', '8'], ['Wind_Speed_kmh', 'Wind speed (km/h)', 'number', '12'], ['Crop_Type', 'Crop type', 'text', 'Rice'], ['Crop_Growth_Stage', 'Growth stage', 'text', 'Vegetative'], ['Season', 'Season', 'text', 'Kharif'], ['Irrigation_Type', 'Irrigation type', 'text', 'Drip'], ['Water_Source', 'Water source', 'text', 'Canal'], ['Field_Area_hectare', 'Field area (ha)', 'number', '2'], ['Mulching_Used', 'Mulching used', 'text', 'Yes'], ['Previous_Irrigation_mm', 'Previous irrigation (mm)', 'number', '25'], ['Region', 'Region', 'text', 'Central']] },
  price: { title: 'Price prediction', endpoint: '/price/predict', resultKey: 'predicted_price', resultLabel: 'Predicted price', tone: 'amber', fields: [['month', 'Month', 'month', '2026-09'], ['commodity_name', 'Commodity', 'text', 'Rice'], ['avg_min_price', 'Average minimum price', 'number', '1800'], ['avg_max_price', 'Average maximum price', 'number', '2400'], ['state_name', 'State', 'text', 'India'], ['district_name', 'District', 'text', 'All'], ['calculationType', 'Calculation type', 'text', 'Monthly'], ['change', 'Change (%)', 'number', '0']] },
  yield: { title: 'Yield prediction', endpoint: '/yield/predict', resultKey: 'predicted_yield_t_per_ha', resultLabel: 'Predicted yield', tone: 'orange', fields: [['Crop_Type', 'Crop type', 'text', 'Rice'], ['Field_Size_ha', 'Field size (ha)', 'number', '2'], ['Planting_Date', 'Planting date', 'date', '2026-06-15'], ['Soil_Type', 'Soil type', 'text', 'Loamy'], ['Fertilizer_Used', 'Fertilizer used', 'text', 'Urea'], ['Irrigation_Type', 'Irrigation type', 'text', 'Drip']] },
};

function App() {
  const [theme, setTheme] = useState(() => localStorage.getItem('fieldly-theme') || 'system');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const location = useLocation();
  const pageTitle = navItems.find((item) => item.to === location.pathname)?.label || formConfigs[location.pathname.split('/')[2]]?.title || 'Service';
  useEffect(() => {
    const media = window.matchMedia('(prefers-color-scheme: dark)');
    const apply = () => document.documentElement.setAttribute('data-theme', theme === 'system' ? (media.matches ? 'dark' : 'light') : theme);
    apply(); localStorage.setItem('fieldly-theme', theme); media.addEventListener?.('change', apply);
    return () => media.removeEventListener?.('change', apply);
  }, [theme]);
  return <div className="app-shell"><aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><Leaf size={18} /></div><span>field.ly</span></div><div className="sidebar-kicker">Farm intelligence</div><nav className="sidebar-nav">{navItems.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={() => setSidebarOpen(false)}><Icon size={18} /><span>{label}</span></NavLink>)}</nav><div className="sidebar-footer"><span className="status-dot status-good" />ML services online</div></aside>{sidebarOpen && <button className="scrim" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}<main className="shell-main"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-toggle" aria-label="Toggle menu" onClick={() => setSidebarOpen(!sidebarOpen)}>{sidebarOpen ? <X size={18} /> : <Menu size={18} />}</button><div><div className="page-kicker">Field intelligence</div><div className="page-title">{pageTitle}</div></div></div><div className="topbar-actions"><button className="icon-button" aria-label="Notifications"><Bell size={18} /><span className="notification-dot" /></button><button className="theme-button" aria-label="Toggle dark mode" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun size={16} /> : <Moon size={16} />}</button></div></header><div className="container"><Routes><Route path="/" element={<Dashboard />} /><Route path="/fields" element={<FieldsPage />} /><Route path="/recommendations" element={<RecommendationsPage />} /><Route path="/insights" element={<InsightsPage />} /><Route path="/weather" element={<WeatherPage />} /><Route path="/settings" element={<SettingsPage theme={theme} setTheme={setTheme} />} /><Route path="/services/:service" element={<ServicePage />} /></Routes></div></main></div>;
}

function StatCard({ label, value, trend, icon: Icon, tone = 'green' }) { return <div className="stat-card"><div className="stat-top"><span className={`stat-icon ${tone}`}><Icon size={17} /></span><span className="stat-trend">{trend}</span></div><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div>; }

function Dashboard() {
  const [weather, setWeather] = useState(null);
  useEffect(() => { requestJson('/weather/current').then(setWeather).catch((error) => setWeather({ configured: false, message: error.message })); }, []);
  return <><section className="hero"><div className="hero-copy"><div className="eyebrow">Monday, September 7, 2026</div><h1>Smarter farming.<br /><em>Better decisions.</em></h1><p>Good morning, Farm Manager. Here is the signal from your operation today.</p><div className="hero-actions"><a className="primary-button" href="/services/crop">Run a crop check <ChevronRight size={16} /></a><a className="secondary-button" href="/fields">View my fields</a></div></div><div className="hero-weather"><div className="section-header"><span className="eyebrow">Field conditions</span><CloudSun size={20} /></div>{weather?.configured ? <><strong>{weather.temperature}°</strong><span>{weather.condition}</span><div className="weather-mini"><span>Humidity {weather.humidity}%</span><span>Wind {weather.wind_speed} km/h</span></div></> : <div className="empty-state compact">{weather?.message || 'Loading weather...'}</div>}</div></section><section className="stat-grid"><StatCard label="Active growing area" value="12.8 ha" trend="+8.2%" icon={Wheat} /><StatCard label="Water efficiency" value="81%" trend="+11.0%" icon={Droplets} tone="blue" /><StatCard label="Expected yield" value="4.6 t/ha" trend="+5.1%" icon={TrendingUp} tone="amber" /><StatCard label="Healthy fields" value="82%" trend="+2.1%" icon={Leaf} /></section><section className="section-heading"><div><div className="eyebrow">Decision tools</div><h2>Smart farm services</h2></div><span className="muted">Powered by your trained models</span></section><div className="service-grid">{services.map((service) => <ServiceCard key={service.key} {...service} serviceKey={service.key} />)}</div><section className="dashboard-lower"><div className="card"><div className="section-header"><h3 className="section-title">Today&apos;s focus</h3><span className="badge badge-amber">3 actions</span></div><div className="focus-list"><div><span className="focus-number">01</span><span><strong>Review soil balance</strong><small>Run a fertilizer recommendation for South Valley.</small></span></div><div><span className="focus-number">02</span><span><strong>Plan the next irrigation</strong><small>Soil moisture is approaching the action threshold.</small></span></div><div><span className="focus-number">03</span><span><strong>Check market timing</strong><small>Compare today&apos;s expected price before harvest.</small></span></div></div></div><div className="card quote-card"><span className="eyebrow">Farm note</span><p>“The best time to make a small adjustment is before the field asks for a big one.”</p><span className="muted">field.ly intelligence brief</span></div></section></>;
}

function ServiceCard({ key: serviceKey, title, description, icon: Icon, tone }) { return <a className="service-card" href={`/services/${serviceKey}`}><div className={`service-icon ${tone}`}><Icon size={22} /></div><div><h3>{title}</h3><p>{description}</p></div><ChevronRight className="service-arrow" size={18} /></a>; }
function ServicePage() { const { pathname } = useLocation(); const service = pathname.split('/')[2]; return <PredictionForm config={formConfigs[service] || formConfigs.crop} service={service} />; }
function PredictionForm({ config, service }) {
  const initial = useMemo(() => Object.fromEntries(config.fields.map(([key, , type, value]) => [key, type === 'number' ? Number(value) : value])), [config]);
  const [values, setValues] = useState(initial); const [state, setState] = useState({ loading: false, error: null, result: null });
  const submit = async (event) => { event.preventDefault(); setState({ loading: true, error: null, result: null }); try { const result = await requestJson(config.endpoint, { method: 'POST', body: JSON.stringify(values) }); setState({ loading: false, error: null, result }); } catch (error) { setState({ loading: false, error: error.message, result: null }); } };
  return <div className="service-page"><div className="service-intro"><div className={`service-icon ${config.tone}`}><Zap size={22} /></div><div><div className="eyebrow">Live model service</div><h1>{config.title}</h1><p>Use the same feature schema as the trained model. Results are generated by your backend.</p></div></div><div className="prediction-layout"><form className="card prediction-form" onSubmit={submit}><div className="section-header"><h2 className="section-title">Field conditions</h2><span className="badge badge-green">Validated inputs</span></div><div className="form-grid">{config.fields.map(([key, label, type]) => <div className="field" key={key}><label htmlFor={key}>{label}<span className="required">*</span></label><input id={key} type={type} required value={values[key]} onChange={(event) => setValues({ ...values, [key]: type === 'number' ? Number(event.target.value) : event.target.value })} /></div>)}</div><button className="primary-button submit-button" disabled={state.loading}>{state.loading ? 'Analyzing field...' : 'Generate recommendation'} <ChevronRight size={16} /></button></form><div className="card result-panel"><div className="section-header"><h2 className="section-title">Model result</h2><span className={`badge badge-${config.tone === 'orange' ? 'amber' : config.tone}`}>Live</span></div>{state.loading ? <div className="loading-state"><span className="loader" />Evaluating conditions...</div> : state.error ? <div className="error-state"><strong>Prediction unavailable</strong><p>{state.error}</p><button type="button" className="secondary-button" onClick={() => setState({ loading: false, error: null, result: null })}>Try again</button></div> : state.result ? <div className="result-box"><div className="eyebrow">{config.resultLabel}</div><div className="result-value">{state.result[config.resultKey]}{serviceUnit(config.resultKey, state.result)}</div><p>{state.result.reasoning || state.result.recommendation || 'Based on the supplied field conditions and the trained model output.'}</p><details><summary>Input summary</summary><pre>{JSON.stringify(state.result.input_summary || values, null, 2)}</pre></details></div> : <div className="empty-state">Submit the field conditions to see a real model result.</div>}</div></div></div>;
}
function serviceUnit(key, result) { if (key === 'predicted_price') return ` ${result.currency || ''}`; if (key === 'predicted_yield_t_per_ha') return ` ${result.unit || 't/ha'}`; return ''; }

function FieldsPage() { const fields = [{ name: 'North Plot', crop: 'Rice', area: '4.2 ha', status: 'Healthy', progress: 72 }, { name: 'South Valley', crop: 'Maize', area: '3.1 ha', status: 'Needs attention', progress: 48 }, { name: 'East Terrace', crop: 'Wheat', area: '2.6 ha', status: 'Monitoring', progress: 31 }]; return <><div className="section-heading"><div><div className="eyebrow">Your operation</div><h1>My fields</h1></div><button className="primary-button">Add field <span>+</span></button></div><div className="field-grid">{fields.map((field) => <div className="card field-card" key={field.name}><div className="field-card-top"><span className={`status-badge ${field.status === 'Healthy' ? 'good' : field.status === 'Monitoring' ? 'info' : 'warn'}`}>{field.status}</span><button className="icon-button" aria-label={`Open ${field.name}`}>...</button></div><h2>{field.name}</h2><p>{field.crop} · {field.area}</p><div className="progress-label"><span>Season progress</span><strong>{field.progress}%</strong></div><div className="progress"><span style={{ width: `${field.progress}%` }} /></div><div className="field-meta"><span>Last updated 2h ago</span><a href="/services/irrigation">Review field <ChevronRight size={14} /></a></div></div>)}</div></>; }
function RecommendationsPage() { return <><div className="section-heading"><div><div className="eyebrow">Next best actions</div><h1>Recommendations</h1></div><span className="badge badge-green">3 new</span></div><div className="recommendation-list">{[['Crop recommendation', 'North Plot has suitable conditions for rice this season.', '93%', 'Review crop model', 'green'], ['Fertilizer plan', 'South Valley is ready for a potassium-focused application.', '89%', 'Open fertilizer model', 'purple'], ['Irrigation action', 'East Terrace can reduce the next cycle after rainfall.', '86%', 'Check irrigation', 'blue']].map(([type, text, confidence, action, tone]) => <div className="card recommendation" key={type}><div className={`service-icon ${tone}`}><Sprout size={20} /></div><div className="recommendation-copy"><div className="eyebrow">{type}</div><h2>{text}</h2><span className="muted">North Plot · Today</span></div><div className="recommendation-action"><strong>{confidence}</strong><a className="secondary-button" href="/services/crop">{action}</a></div></div>)}</div></>; }
function InsightsPage() { return <><div className="section-heading"><div><div className="eyebrow">Operational analytics</div><h1>Insights</h1></div><span className="muted">Last 30 days</span></div><div className="insight-grid"><div className="card chart-card wide"><div className="section-header"><h2 className="section-title">Yield outlook</h2><span className="badge badge-green">+5.1%</span></div><div className="chart-bars">{[42, 58, 51, 68, 64, 78, 72, 88, 81, 94, 86, 100].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div><div className="card"><div className="eyebrow">Resource health</div><h2 className="big-stat">81%</h2><p className="muted">Water efficiency across monitored fields</p><div className="progress"><span style={{ width: '81%' }} /></div></div><div className="card"><div className="eyebrow">Field health</div><h2 className="big-stat">82%</h2><p className="muted">Healthy growing area this week</p><div className="progress amber-progress"><span style={{ width: '82%' }} /></div></div></div></>; }
function WeatherPage() { const [weather, setWeather] = useState(null); useEffect(() => { requestJson('/weather/current').then(setWeather).catch((error) => setWeather({ configured: false, message: error.message })); }, []); return <div className="weather-page"><div className="section-heading"><div><div className="eyebrow">Live conditions</div><h1>Weather station</h1></div><span className={`badge ${weather?.configured ? 'badge-blue' : 'badge-amber'}`}>{weather?.configured ? 'Connected' : 'Configuration needed'}</span></div>{!weather ? <div className="empty-state">Loading weather data...</div> : weather.configured ? <div className="weather-grid"><div className="card weather-main"><CloudSun size={30} /><strong>{weather.temperature}°C</strong><h2>{weather.condition}</h2><span className="muted">Live observation from OpenWeather</span></div><div className="card metric-list"><div className="metric-item"><span>Humidity</span><strong>{weather.humidity}%</strong></div><div className="metric-item"><span>Wind</span><strong>{weather.wind_speed} km/h</strong></div><div className="metric-item"><span>Cloud coverage</span><strong>{weather.cloud_coverage}%</strong></div><div className="metric-item"><span>Sunrise / sunset</span><strong>{weather.sunrise} / {weather.sunset}</strong></div></div></div> : <div className="card configuration-state"><CloudSun size={32} /><h2>Weather service isn&apos;t configured yet.</h2><p>{weather.message || 'Set OPENWEATHER_API_KEY on the backend to enable live conditions.'}</p><code>OPENWEATHER_API_KEY=your-key</code></div>}</div>; }
function SettingsPage({ theme, setTheme }) { return <div className="settings-grid"><div className="card"><div className="eyebrow">Personalize</div><h1>Settings</h1><div className="field"><label htmlFor="themeMode">Appearance</label><select id="themeMode" value={theme} onChange={(event) => setTheme(event.target.value)}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></div></div><div className="card"><div className="eyebrow">Preferences</div><h2>Farm notifications</h2><div className="settings-list"><label><span><strong>Weather alerts</strong><small>Rain, wind, and temperature warnings</small></span><input type="checkbox" defaultChecked /></label><label><span><strong>Weekly farm digest</strong><small>A summary every Monday morning</small></span><input type="checkbox" defaultChecked /></label><label><span><strong>Recommendation updates</strong><small>New model insights for your fields</small></span><input type="checkbox" defaultChecked /></label></div></div></div>; }

export default App;
